export const MAX_REFRESH_INTERVAL_MINUTES = 5
export const MIN_REFRESH_INTERVAL_MINUTES = 1

export const MIN_REFRESH_DELAY_SECONDS = 10
export const TOKEN_REFRESH_LIFETIME_FRACTION = 0.6

export const INITIAL_ERROR_BACKOFF_SECONDS = 15
export const MAX_ERROR_BACKOFF_STEP = 7
