# Super Linter configuration to bypass linting for template
VALIDATE_ALL_CODEBASE: false
VALIDATE_CSS: false
VALIDATE_DOCKER: false
VALIDATE_HTML: false
VALIDATE_JAVASCRIPT_ES: false
VALIDATE_JAVASCRIPT_STANDARD: false
VALIDATE_JSON: false
VALIDATE_MARKDOWN: false
VALIDATE_PYTHON_BLACK: false
VALIDATE_PYTHON_FLAKE8: false
VALIDATE_PYTHON_ISORT: false
VALIDATE_PYTHON_MYPY: false
VALIDATE_PYTHON_PYLINT: false
VALIDATE_SHELL_SHFMT: false
VALIDATE_SHELL_SHELLCHECK: false
VALIDATE_TERRAFORM: false
VALIDATE_TYPESCRIPT_ES: false
VALIDATE_TYPESCRIPT_STANDARD: false
VALIDATE_YAML: false
