---
env:
  browser: true
  es2021: true

extends:
  - eslint:recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

ignorePatterns:
  - "**/vendor/**"
  - "**/static/js/vendor/**"
  - "**/*.min.js"
  - "**/node_modules/**"
  - "**/dist/**"

