---
name: Deploy Asset Metadata to App Engine

on:
  push:
    branches:
      - 'master'
    paths:
      - 'asset-metadata/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Replace credentials
        run: |
          sed -i "s/GOOGLE_MAPS_API_KEY_VAL/${{ secrets.GOOGLE_MAPS_API_KEY }}/g" asset-metadata/app.yaml

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          deliverables: 'app.yaml'
          working_directory: 'asset-metadata'
          project_id: '${{ secrets.GCP_PROJECT }}'

      - id: 'test'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
