---
name: Deploy Weather App

on:
  push:
    branches:
      - 'master'
    paths:
      - 'edge-apps/weather/**'
      - '.github/workflows/deploy-weather-app.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: edge-apps/weather

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build containers
        run: |
          docker build \
            -t screenly/weather-app \
            -f Dockerfile \
            .

      - name: Build static page
        run: |
          docker run --rm \
            -e GA_API_KEY="${{ secrets.CLOCK_APP_GA_API_KEY }}" \
            -e SENTRY_ID="${{ secrets.CLOCK_APP_SENTRY_ID }}" \
            -e OPEN_WEATHER_API_KEY="${{ secrets.OPEN_WEATHER_API_KEY }}" \
            -v "$(pwd)"/src:/usr/app/src \
            -v "$(pwd)"/dist:/usr/app/dist \
            screenly/weather-app

      - name: Deploy Edge App
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN }}
          # yamllint disable-line rule:line-length
          cli_commands: asset add edge-apps/weather/dist/index.html "Playground Weather Edge App ($GITHUB_SHA)"

      - name: Deploy Edge App
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN_WLVIKTOR }}
          # yamllint disable-line rule:line-length
          cli_commands: asset add edge-apps/weather/dist/index.html "Playground Weather Edge App ($GITHUB_SHA)"
