---
name: Deploy tfl bus status app

on:
  workflow_dispatch:

#  push:
#    branches:
#      - 'master'
#    paths:
#      - 'edge-apps/tfl-bus-status/**'
#      - '.github/workflows/deploy-tfl-bus-status.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_PATH: 'edge-apps/tfl-bus-status'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Edge App
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN_PRODUCTION }}
          # yamllint disable-line rule:line-length
          cli_commands: edge-app deploy --path=${{ env.APP_PATH }}
