---
name: Deploy Weather App (QC)

on:
  push:
    branches:
      - 'master'
    paths:
      - 'edge-apps/weather/**'
      - '.github/workflows/deploy-weather-app.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_PATH: 'edge-apps/weather'
      MANIFEST_FILE_NAME: 'screenly_qc.yml'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Edge App
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN_AUTOMATED_QC }}
          # yamllint disable-line rule:line-length
          cli_commands: edge-app deploy --path=${{ env.APP_PATH }}
