---
name: Deploy Asset Metadata to App Engine

on:
  push:
    branches-ignore: [master, main]

jobs:
  job_id:
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v0'
      working_directory: asset-metadata

    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
