---
name: Deploy Clock App (QC)

on:
  push:
    branches:
      - 'master'
    paths:
      - 'edge-apps/clock/**'
      - '.github/workflows/deploy-clock-app-qc.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_ID: '01HKT1XSC070BGNKYR7ZE689DE'
      INSTALLATION_ID: ''

      APP_PATH: 'edge-apps/clock'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Edge App
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN_AUTOMATED_QC }}
          # yamllint disable-line rule:line-length
          cli_commands: edge-app upload --app-id=${{ env.APP_ID }} --path=${{ env.APP_PATH }}

      - name: List Versions
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN_AUTOMATED_QC }}
          # yamllint disable-line rule:line-length
          cli_commands: edge-app version list --app-id=${{ env.APP_ID }}

      - name: Promote Edge App
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN_AUTOMATED_QC }}
          # yamllint disable-line rule:line-length
          cli_commands: edge-app version promote --latest --installation-id=${{ env.INSTALLATION_ID }} --path=${{ env.APP_PATH }}
