---
name: Deploy RSS Reader App

on:
  push:
    branches:
      - 'master'
    paths:
      - 'edge-apps/rss-reader/**'
      - '.github/workflows/deploy-rss-reader.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_ID: '01H8PFEZDA5THTPQ7Y19Z9KDQ0'

    defaults:
      run:
        working-directory: edge-apps/rss-reader

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Edge App
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN }}
          # yamllint disable-line rule:line-length
          cli_commands: edge-app upload --app-id=${{ env.APP_ID }}

      - name: Get Revisions
        id: get_revisions
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN }}
          # yamllint disable-line rule:line-length
          cli_commands: edge-app version list --app-id=${{ env.APP_ID }} --json

      - name: Latest Revision
        # Using `jq` to extract the latest revision
        id: latest_revision
        # yamllint disable-line rule:line-length
        run: echo "revision=$(echo ${{ steps.get_revisions.stdout.value }} | jq '.[-1:] | .[].revision')" >> "$GITHUB_OUTPUT"

      - name: Promote Edge App
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN }}
          # yamllint disable-line rule:line-length
          cli_commands: edge-app version promote --revision=${{ steps.latest_revision.outputs.revision }} --channel=candidate --app-id=${{ env.APP_ID }}
