---
name: Deploy Asset Metadata to App Engine

on:
  push:
    branches-ignore: [master, main]

jobs:
  runs-on: ubuntu-latest
  job_id:
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'
        working_directory: ${{ github.workspace }}/asset-metadata/

      - id: 'test'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
