---
name: Deploy Clock App (QC)

on:
  push:
    branches:
      - 'master'
    paths:
      - 'edge-apps/clock/**'
      - '.github/workflows/deploy-clock-app-qc.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_PATH: 'edge-apps/clock'
      MANIFEST_FILE_NAME: 'screenly_qc.yml'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Edge App
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN_AUTOMATED_QC }}
          # yamllint disable-line rule:line-length
          cli_commands: edge-app deploy --path=${{ env.APP_PATH }}
