---
name: Deploy Weather App

on:
  push:
    paths:
      - 'edge-apps/weather/**'
      - '.github/workflows/deploy-weather-app.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_ID: '01H8PFEJC8QRQ8DJAWV84NT4HH'
      APP_PATH: 'edge-apps/weather'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Edge App
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN }}
            # yamllint disable-line rule:line-length
          cli_commands: edge-app upload --app-id=${{ env.APP_ID }} --path=${{ env.APP_PATH }}

      - name: Promote Edge App
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN }}
            # yamllint disable-line rule:line-length
          cli_commands: edge-app version promote --latest --channel=candidate --app-id=${{ env.APP_ID }} --path=${{ env.APP_PATH }}
