---
name: Deploy RSS Reader App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_PATH: 'edge-apps/rss-reader'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy in Bootstrap theme
        run: |
          cd edge-apps/rss-reader
          mkdir -p bootstrap/theme
          cp -r ../../bootstrap/theme/ ./bootstrap/

      - name: Deploy Edge App
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN_PRODUCTION }}
          # yamllint disable-line rule:line-length
          cli_commands: edge-app deploy --path=${{ env.APP_PATH }}
