---
name: Deploy iframe app

on:
  push:
    branches:
      - 'master'
    paths:
      - 'edge-apps/iframe/**'
      - '.github/workflows/deploy-iframe.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_PATH: 'edge-apps/iframe'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Edge App
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN_PRODUCTION }}
          # yamllint disable-line rule:line-length
          cli_commands: edge-app deploy --path=${{ env.APP_PATH }}
