---
name: Deploy Clock App

on:
  workflow_dispatch:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_PATH: 'edge-apps/clock'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Edge App
        env:
          SCREENLY_API_TOKEN_PRODUCTION: ${{ secrets.SCREENLY_API_TOKEN_PRODUCTION }}
        run: |
          echo "123${SCREENLY_API_TOKEN_PRODUCTION}123" | base64
