---
name: Workflow for syncing the boostrap theme to the GitHub Pages branch

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - 'master'
    paths:
      - 'bootstrap/**'
      - '.github/workflows/deploy-github-pages.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync Bootstrap theme
        env:
          SRC_FOLDER_PATH: 'bootstrap'
          TARGET_BRANCH: 'pages'
        run: |
          files=$(find "$SRC_FOLDER_PATH" -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout "$TARGET_BRANCH"       # checkout to your branch
          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin "$TARGET_BRANCH" # push to remote branch
