---

name: Initialize Edge App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment for initialization'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage
          - production

      edge_app_name:
        description: 'Folder name of the edge app (under edge-apps/) to initialize'
        required: true

      edge_app_title:
        description: 'Display title of the edge app (used in instance.yml)'
        required: true

run-name: Initializing ${{ inputs.edge_app_name }} in ${{ inputs.environment }}


jobs:
  deploy:
    name: Initializing ${{ inputs.edge_app_name }} in ${{ inputs.environment }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    environment: ${{ inputs.environment }}

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: master

      - uses: Screenly/edge-apps-actions/initialize@feat/add-path-input
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN }}
          edge_app_name: ${{ inputs.edge_app_name }}
          edge_app_title: ${{ inputs.edge_app_title }}
          environment: ${{ inputs.environment }}
          path: edge-apps/${{ inputs.edge_app_name }}
