name: Mark Stale PRs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

env:
  DAYS_BEFORE_STALE: 60
  DAYS_BEFORE_CLOSE: 7

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10.3.0
        with:
          days-before-issue-stale: -1
          days-before-issue-close: -1
          days-before-pr-stale: ${{ env.DAYS_BEFORE_STALE }}
          days-before-pr-close: ${{ env.DAYS_BEFORE_CLOSE }}
          stale-pr-label: 'stale'
          stale-pr-message: >
            This PR has been inactive for ${{ env.DAYS_BEFORE_STALE }} days and has been marked as stale.
            It will be closed in ${{ env.DAYS_BEFORE_CLOSE }} days if there is no further activity.
            Please update the PR or leave a comment if it is still being worked on.
